name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: poetry install

            - name: Setup PyPI Token
              run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

            - name: Build and publish
              run: |
                poetry build
                poetry publish --build
